# Generated by Django 3.2.16 on 2023-07-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0080_dashboardindicatorlayer_type_migrations_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicator',
            name='style_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicatorlayer',
            name='style_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicatorlayerrelatedtable',
            name='style_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='style_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='style_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.')], default='Predefined style/color rules.', max_length=256),
        ),
        migrations.AlterField(
            model_name='dashboardindicator',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Style from library.', max_length=256),
        ),
        migrations.AlterField(
            model_name='dashboardindicatorlayer',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Style from library.', max_length=256),
        ),
        migrations.AlterField(
            model_name='dashboardindicatorlayerrelatedtable',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Style from library.', max_length=256),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Style from library.', max_length=256),
        ),
    ]
