# Generated by Django 3.2.16 on 2023-07-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0081_auto_20230712_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicatorlayerrelatedtablerule',
            name='outline_size',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='dashboardindicatorlayerrule',
            name='outline_size',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='dashboardindicatorrule',
            name='outline_size',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='indicatorrule',
            name='outline_size',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='stylerule',
            name='outline_size',
            field=models.FloatField(default=0.5),
        ),
    ]
