# Generated by Django 3.2.16 on 2023-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0084_auto_20230810_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='enable_geometry_search',
            field=models.BooleanField(default=True),
        ),
    ]
