# Generated by Django 3.2.16 on 2023-09-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0085_dashboard_enable_geometry_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='auto_zoom_to_filter',
            field=models.BooleanField(default=False),
        ),
    ]
