# Generated by Django 3.2.16 on 2023-09-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0085_dashboard_enable_geometry_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardindicator',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Dynamic quantitative style.', max_length=256),
        ),
        migrations.AlterField(
            model_name='dashboardindicatorlayer',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Dynamic quantitative style.', max_length=256),
        ),
        migrations.AlterField(
            model_name='dashboardindicatorlayerindicator',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Dynamic quantitative style.', max_length=256),
        ),
        migrations.AlterField(
            model_name='dashboardindicatorlayerrelatedtable',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Dynamic quantitative style.', max_length=256),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='style_type',
            field=models.CharField(choices=[('Predefined style/color rules.', 'Predefined style/color rules.'), ('Dynamic quantitative style.', 'Dynamic quantitative style.'), ('Dynamic qualitative style.', 'Dynamic qualitative style.'), ('Style from library.', 'Style from library.')], default='Dynamic quantitative style.', max_length=256),
        ),
    ]
