# Generated by Django 3.2.16 on 2023-10-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0086_auto_20230925_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='default_time_mode',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
