# Generated by Django 3.2.16 on 2023-10-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0088_indicator_value_with_geo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['geom_id'], name='indicator_value_geom_id'),
        ),
    ]
