# Generated by Django 3.2.16 on 2023-10-26 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0088_indicator_value_with_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='version_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
