# Generated by Django 3.2.16 on 2023-11-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0091_views_initiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcgisConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('generate_token_url', models.CharField(help_text='You can check your generate token url in <a href="https://developers.arcgis.com/rest/services-reference/enterprise/generate-token.htm">https://developers.arcgis.com/rest/services-reference/enterprise/generate-token.htm</a>.<br>If your arcgis is federated one, please use url : https://{host}:{port}/portal/sharing/rest/generateToken.', max_length=512)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('token', models.TextField(blank=True, help_text='This token will be generated automatically.', null=True)),
                ('expires', models.DateTimeField(blank=True, help_text='The expires date of token.', null=True)),
                ('message', models.TextField(blank=True, help_text='Messasge when generate token error.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
