# Generated by Django 3.2.16 on 2023-11-21 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0091_views_initiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcgisConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('generate_token_url', models.CharField(help_text='You can check your generate token url in <a href="https://developers.arcgis.com/rest/services-reference/enterprise/generate-token.htm">https://developers.arcgis.com/rest/services-reference/enterprise/generate-token.htm</a>.<br>If your arcgis is federated one, please use url : https://{host}:{port}/portal/sharing/generateToken.', max_length=512)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('token', models.TextField(blank=True, help_text='This token will be generated automatically.', null=True)),
                ('expires', models.DateTimeField(blank=True, help_text='The expires date of token.', null=True)),
                ('message', models.TextField(blank=True, help_text='Messasge when generate token error.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='layer_type',
            field=models.CharField(choices=[('ARCGIS', 'ARCGIS'), ('Geojson', 'Geojson'), ('Raster Tile', 'Raster Tile')], default='ARCGIS', help_text='The type of layer for this context layer.<br>For <b>ArcGIS</b>, put feature server of REST. e.g : https://{host}/rest/services/{layer}/FeatureServer/1.<br>For <b>GeoJson</b>, put url of geojson.<br>For <b>Raster tile</b>, put XYZ url.', max_length=256),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='url',
            field=models.CharField(help_text='Put full url with parameters that are needed. ', max_length=10240),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='url_legend',
            field=models.CharField(blank=True, help_text='This is the url of image that will be rendered as legend. ArcGIS type can be generated automatically, but if you fill this url legend, it will be overridden', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='arcgis_config',
            field=models.ForeignKey(blank=True, help_text='ArcGIS configuration that contains username/password that will be used to autogenerate the token.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_data.arcgisconfig'),
        ),
    ]
