# Generated by Django 3.2.16 on 2023-11-21 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0092_arcgisconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextlayer',
            name='arcgis_config',
            field=models.ForeignKey(blank=True, help_text='ArcGis configuration that contains username/password that will be used for autogenerate the token.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_data.arcgisconfig'),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='layer_type',
            field=models.CharField(choices=[('ARCGIS', 'ARCGIS'), ('Geojson', 'Geojson'), ('Raster Tile', 'Raster Tile')], default='ARCGIS', help_text='The type of layer for this context layer.<br>For <b>ArcGIS</b>, put feature server of REST. e.g : https://{host}/rest/services/{layer}/FeatureServer/1.<br>For <b>GeoJson</b>, put url of geojson.<br>For <b>Raster tile</b>, put XYZ url.', max_length=256),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='url',
            field=models.CharField(help_text='Put full url with parameters that are needed. ', max_length=10240),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='url_legend',
            field=models.CharField(blank=True, help_text='This is the url of image that will be rendered as legend. ArcGis type can be generated automatically, but if you fill this url legend, it will be overridden', max_length=256, null=True),
        ),
    ]
