# Generated by Django 3.2.16 on 2023-11-13 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0093_auto_20231121_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='version_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
