# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations

from geosight.data.migrations.sql.utils import load_sql


class Migration(migrations.Migration):
    dependencies = [
        ('geosight_data', '0094_dashboard_version_data'),
    ]

    operations = [
    ]
