# Generated by Django 3.2.16 on 2024-01-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0096_indicatorvaluedataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextlayerfield',
            name='type',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'String'), ('date', 'Date')], default='string', max_length=512),
        ),
        migrations.AlterField(
            model_name='dashboardcontextlayerfield',
            name='type',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'String'), ('date', 'Date')], default='string', max_length=512),
        ),
        migrations.AlterField(
            model_name='dashboardindicatorlayerfield',
            name='type',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'String'), ('date', 'Date')], default='string', max_length=512),
        ),
    ]
