# Generated by Django 3.2.16 on 2024-01-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0098_relatedtablefield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedTableRowEAV',
        ),
    ]
