# Generated by Django 3.2.16 on 2024-01-31 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0099_delete_relatedtableroweav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
    ]
