# Generated by Django 3.2.16 on 2024-03-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0101_auto_20240219_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextlayer',
            name='layer_type',
            field=models.CharField(choices=[('ARCGIS', 'ARCGIS'), ('Geojson', 'Geojson'), ('Raster Tile', 'Raster Tile'), ('Vector Tile', 'Vector Tile')], default='ARCGIS', help_text='The type of layer for this context layer.<br>For <b>ArcGIS</b>, put feature server of REST. e.g : https://{host}/rest/services/{layer}/FeatureServer/1.<br>For <b>GeoJson</b>, put url of geojson.<br>For <b>Raster tile</b>, put XYZ url.<br>For <b>Vector tile</b>, put XYZ url.', max_length=256),
        ),
    ]
