# Generated by Django 3.2.16 on 2024-04-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0103_alter_contextlayer_layer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorValueDataset',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('indicator_id', models.BigIntegerField()),
                ('reference_layer_id', models.UUIDField()),
                ('admin_level', models.IntegerField()),
                ('data_count', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reference_layer_uuid', models.UUIDField()),
                ('reference_layer_name', models.CharField(blank=True, max_length=256, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=256, null=True)),
                ('indicator_shortcode', models.CharField(blank=True, max_length=256, null=True)),
                ('identifier', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='datetime_field',
            field=models.TextField(blank=True, help_text='Datetime field of Related Table.', null=True),
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='latitude_field',
            field=models.TextField(blank=True, help_text='Latitude field of Related Table.', null=True),
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='longitude_field',
            field=models.TextField(blank=True, help_text='Longitude field of Related Table.', null=True),
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='query',
            field=models.TextField(blank=True, help_text='Query to filter Related Table data.', null=True),
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='related_table',
            field=models.ForeignKey(blank=True, help_text='Related table name.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_data.relatedtable'),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='layer_type',
            field=models.CharField(choices=[('ARCGIS', 'ARCGIS'), ('Geojson', 'Geojson'), ('Raster Tile', 'Raster Tile'), ('Vector Tile', 'Vector Tile'), ('Related Table', 'Related Table')], default='ARCGIS', help_text='The type of layer for this context layer.<br>For <b>ArcGIS</b>, put feature server of REST. e.g : https://{host}/rest/services/{layer}/FeatureServer/1.<br>For <b>GeoJson</b>, put url of geojson.<br>For <b>Raster tile</b>, put XYZ url.<br>For <b>Related Table</b>, select existing related table name.For <b>Vector tile</b>, put XYZ url.', max_length=256),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='url',
            field=models.CharField(blank=True, help_text='Put full url with parameters that are needed. Not necesary for Related Table Layer Type.', max_length=10240, null=True),
        ),
    ]
