# Generated by Django 3.2.16 on 2024-05-14 07:07
import json

from django.db import migrations, models, connection

from geosight.data.models.context_layer import ContextLayer


def run(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT id, latitude_field,longitude_field, query '
            "FROM geosight_data_contextlayer WHERE layer_type='Related Table'"
        )
        for context_layer in cursor.fetchall():
            _id = context_layer[0]
            latitude_field = context_layer[1]
            longitude_field = context_layer[2]
            query = context_layer[3]
            try:
                obj = ContextLayer.objects.get(id=_id)
                obj.configuration = json.dumps({
                    'latitude_field': latitude_field,
                    'longitude_field': longitude_field,
                    'query': query
                })
                obj.save()
                obj.update_dashboard_version()
            except ContextLayer.DoesNotExist:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ('geosight_data', '0104_auto_20240401_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextlayer',
            name='datetime_field',
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(run, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contextlayer',
            name='latitude_field',
        ),
        migrations.RemoveField(
            model_name='contextlayer',
            name='longitude_field',
        ),
        migrations.RemoveField(
            model_name='contextlayer',
            name='query',
        ),
        migrations.AddField(
            model_name='dashboardcontextlayer',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
