# Generated by Django 3.2.16 on 2024-02-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geosight_data', '0104_auto_20240401_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='geo_field',
            field=models.CharField(default='geometry_code', max_length=64),
        ),
    ]
