# Generated by Django 3.2.16 on 2024-04-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0105_auto_20240220_0516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
    ]
