# Generated by Django 3.2.16 on 2024-05-27 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0105_auto_20240514_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedtable',
            name='version_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
