# Generated by Django 3.2.16 on 2024-06-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_cloud_native_gis', '0001_initial'),
        ('geosight_data', '0106_relatedtable_version_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextlayer',
            name='cloud_native_gis_layer',
            field=models.ForeignKey(blank=True, help_text='Using layer from cloud native gis.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_cloud_native_gis.cloudnativegislayer'),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='layer_type',
            field=models.CharField(choices=[('ARCGIS', 'ARCGIS'), ('Geojson', 'Geojson'), ('Raster Tile', 'Raster Tile'), ('Vector Tile', 'Vector Tile'), ('Related Table', 'Related Table'), ('Cloud Native GIS Layer', 'Cloud Native GIS Layer')], default='ARCGIS', help_text='The type of layer for this context layer.<br>For <b>ArcGIS</b>, put feature server of REST. e.g : https://{host}/rest/services/{layer}/FeatureServer/1.<br>For <b>GeoJson</b>, put url of geojson.<br>For <b>Raster tile</b>, put XYZ url.<br>For <b>Related table</b>, select existing related table name.For <b>Vector tile</b>, put XYZ url.For <b>Cloud native gis layer</b>, select the layer from cloud native gis.', max_length=256),
        ),
    ]
