# Generated by Django 3.2.16 on 2024-07-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0106_relatedtable_version_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
    ]
