# Generated by Django 3.2.16 on 2024-07-23 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud_native_gis', '0001_initial'),
        ('geosight_data', '0106_relatedtable_version_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='cloud_native_gis_layer',
            field=models.ForeignKey(blank=True, help_text='Using layer from cloud native gis.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_native_gis.layer'),
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_basemaplayer_related', related_query_name='geosight_data_basemaplayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_contextlayer_related', related_query_name='geosight_data_contextlayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='layer_type',
            field=models.CharField(choices=[('ARCGIS', 'ARCGIS'), ('Geojson', 'Geojson'), ('Raster Tile', 'Raster Tile'), ('Vector Tile', 'Vector Tile'), ('Related Table', 'Related Table'), ('Cloud Native GIS Layer', 'Cloud Native GIS Layer')], default='ARCGIS', help_text='The type of layer for this context layer.<br>For <b>ArcGIS</b>, put feature server of REST. e.g : https://{host}/rest/services/{layer}/FeatureServer/1.<br>For <b>GeoJson</b>, put url of geojson.<br>For <b>Raster tile</b>, put XYZ url.<br>For <b>Related table</b>, select existing related table name.For <b>Vector tile</b>, put XYZ url.For <b>Cloud native gis layer</b>, select the layer from cloud native gis.', max_length=256),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_dashboard_related', related_query_name='geosight_data_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardembed',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_dashboardembed_related', related_query_name='geosight_data_dashboardembeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_indicator_related', related_query_name='geosight_data_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatedtable',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_relatedtable_related', related_query_name='geosight_data_relatedtables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='style',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_style_related', related_query_name='geosight_data_styles', to=settings.AUTH_USER_MODEL),
        ),
    ]
