# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations

from geosight.data.migrations.sql.utils import load_sql


class Migration(migrations.Migration):
    dependencies = [
        ('geosight_data', '0107_views_initiation'),
    ]

    defaults = load_sql('views', 'default.sql')
    views = load_sql('views', 'views.sql')

    operations = [
        migrations.RunSQL(defaults, defaults),
        migrations.RunSQL(views, defaults),
        migrations.AlterModelTable(
            name='indicatorvaluewithgeo',
            table='v_indicator_value_geo',
        ),
    ]
