# Generated by Django 3.2.16 on 2024-07-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0107_auto_20240715_0539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
    ]
