# Generated by Django 3.2.16 on 2024-06-06 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_data', '0107_auto_20240606_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorValueDataset',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('indicator_id', models.BigIntegerField()),
                ('reference_layer_id', models.UUIDField()),
                ('admin_level', models.CharField(max_length=256)),
                ('data_count', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reference_layer_uuid', models.UUIDField()),
                ('reference_layer_name', models.CharField(blank=True, max_length=256, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=256, null=True)),
                ('indicator_shortcode', models.CharField(blank=True, max_length=256, null=True)),
                ('identifier', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_basemaplayer_related', related_query_name='geosight_data_basemaplayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_contextlayer_related', related_query_name='geosight_data_contextlayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_dashboard_related', related_query_name='geosight_data_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardembed',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_dashboardembed_related', related_query_name='geosight_data_dashboardembeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_indicator_related', related_query_name='geosight_data_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatedtable',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_relatedtable_related', related_query_name='geosight_data_relatedtables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='style',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_style_related', related_query_name='geosight_data_styles', to=settings.AUTH_USER_MODEL),
        ),
    ]
