# Generated by Django 3.2.16 on 2024-09-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0108_views_initiation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
    ]
