# Generated by Django 3.2.16 on 2024-07-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0108_auto_20240606_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
    ]
