# Generated by Django 3.2.16 on 2024-08-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0108_indicator_layer_data_updates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='geo_field',
            field=models.CharField(default='geometry_code', max_length=64),
        ),
    ]
