# Generated by Django 3.2.16 on 2024-08-31 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('geosight_data', '0109_auto_20240812_0241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
