# Generated by Django 3.2.16 on 2024-09-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0110_indicator_layer_data_updates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
    ]
