# Generated by Django 3.2.16 on 2024-11-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0111_delete_indicatorvaluedataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorValueDataset',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('indicator_id', models.BigIntegerField()),
                ('reference_layer_id', models.UUIDField()),
                ('admin_level', models.CharField(max_length=256)),
                ('data_count', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reference_layer_uuid', models.UUIDField()),
                ('reference_layer_name', models.CharField(blank=True, max_length=256, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=256, null=True)),
                ('indicator_shortcode', models.CharField(blank=True, max_length=256, null=True)),
                ('identifier', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
