# Generated by Django 3.2.16 on 2025-01-14 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_data', '0113_dashboardtool_indicatorvaluedataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemaplayer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_basemaplayer_modified_by_related', related_query_name='geosight_data_basemaplayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_contextlayer_modified_by_related', related_query_name='geosight_data_contextlayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_dashboard_modified_by_related', related_query_name='geosight_data_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardembed',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_dashboardembed_modified_by_related', related_query_name='geosight_data_dashboardembeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_indicator_modified_by_related', related_query_name='geosight_data_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatedtable',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_relatedtable_modified_by_related', related_query_name='geosight_data_relatedtables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='style',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_data_style_modified_by_related', related_query_name='geosight_data_styles', to=settings.AUTH_USER_MODEL),
        ),
    ]
