# Generated by Django 3.2.16 on 2025-01-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0115_auto_20250116_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='icons/thumbnails'),
        ),
    ]
