# Generated by Django 3.2.16 on 2025-02-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0115_auto_20250116_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='COGClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('type', models.CharField(choices=[('Equidistant.', 'Equidistant.'), ('Natural breaks.', 'Natural breaks.'), ('Quantile.', 'Quantile.'), ('Std deviation.', 'Std deviation.'), ('Arithmetic progression.', 'Arithmetic progression.'), ('Geometric progression.', 'Geometric progression.')], default='Equidistant.', max_length=30)),
                ('number', models.IntegerField(default=7, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'unique_together': {('url', 'type', 'number', 'minimum', 'maximum')},
            },
        ),
    ]
