# Generated by Django 3.2.16 on 2025-02-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0022_entity_country'),
        ('geosight_data', '0118_views_initiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='admin_level',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='concept_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='This is concept uuid from georepo.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_value_country', to='geosight_georepo.entity'),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='country_name',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='entity_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='entity_start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='indicator_name',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='indicator_shortcode',
            field=models.CharField(blank=True, db_index=True, help_text='A computer-to-computer shortcode for this indicator. For example, an abbreviated name that you might use to refer to it in a spreadsheet column.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='indicator_type',
            field=models.CharField(blank=True, choices=[('Integer', 'Integer'), ('Float', 'Float'), ('String', 'Category')], db_index=True, max_length=256, null=True),
        ),
    ]
