# Generated by Django 3.2.16 on 2025-03-02 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0023_referencelayerview_countries'),
        ('geosight_data', '0118_views_initiation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indicatorvalue',
            name='indicator_value_geom_id',
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_value_country', to='geosight_georepo.entity'),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='country_geom_id',
            field=models.CharField(blank=True, help_text='This is ucode from georepo.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='country_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='entity_admin_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='entity_concept_uuid',
            field=models.CharField(blank=True, help_text='This is concept uuid from georepo.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='entity_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='entity_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='entity_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='indicator_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='indicator_shortcode',
            field=models.CharField(blank=True, help_text='A computer-to-computer shortcode for this indicator. For example, an abbreviated name that you might use to refer to it in a spreadsheet column.', max_length=512, null=True),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['geom_id'], name='geosight_da_geom_id_d2dc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator', 'country_id'], name='geosight_da_indicat_317ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator', 'country_id', 'entity_admin_level'], name='geosight_da_indicat_98c856_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator', 'entity_admin_level'], name='geosight_da_indicat_c717da_idx'),
        ),
    ]
