# Generated by Django 3.2.16 on 2025-02-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0119_auto_20250220_0857'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indicatorvalue',
            name='geosight_da_indicat_288525_idx',
        ),
        migrations.RemoveIndex(
            model_name='indicatorvalue',
            name='geosight_da_indicat_9a499e_idx',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='admin_level',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='concept_uuid',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='entity_end_date',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='entity_name',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='entity_start_date',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='indicator_name',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='indicator_shortcode',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='indicator_type',
        ),
    ]
