# Generated by Django 3.2.16 on 2025-02-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0119_auto_20250219_0443'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['country_id'], name='geosight_da_country_6d603e_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator', 'country_id'], name='geosight_da_indicat_317ac9_idx'),
        ),
    ]
