# Generated by Django 3.2.16 on 2025-03-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0120_auto_20250312_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardbookmark',
            name='selected_indicator_layer',
        ),
        migrations.RemoveField(
            model_name='dashboardembed',
            name='selected_indicator_layer',
        ),
    ]
