# Generated by Django 3.2.16 on 2025-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0123_auto_20250526_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='transparency_config',
            field=models.JSONField(blank=True, default={'contextLayer': 100, 'indicatorLayer': 100}, null=True),
        ),
        migrations.AddField(
            model_name='dashboardbookmark',
            name='transparency_config',
            field=models.JSONField(blank=True, default={'contextLayer': 100, 'indicatorLayer': 100}, null=True),
        ),
        migrations.AddField(
            model_name='dashboardembed',
            name='transparency_config',
            field=models.JSONField(blank=True, default={'contextLayer': 100, 'indicatorLayer': 100}, null=True),
        ),
    ]
