# Generated by Django 3.2.16 on 2025-08-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0124_auto_20250616_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='hide_context_layer_tab',
            field=models.BooleanField(default=False),
        ),
    ]
