# Generated by Django 3.2.16 on 2025-08-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0125_dashboard_hide_context_layer_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='enable_geometry_search',
        ),
        migrations.AlterField(
            model_name='dashboardtool',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
