# Generated by Django 3.2.16 on 2025-08-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0126_auto_20250813_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='hide_context_layer_tab',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='layer_tabs_visibility',
            field=models.CharField(blank=True, default='indicator_layers,context_layers', max_length=64, null=True),
        ),
    ]
