# Generated by Django 3.2.16 on 2025-08-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0127_auto_20250817_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='show_map_toolbar',
            field=models.BooleanField(blank=True, default=True, help_text='Show map toolbars on the map.', null=True),
        ),
    ]
