# Generated by Django 3.2.16 on 2025-09-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0128_dashboard_show_map_toolbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicatorlayer',
            name='raw_data_popup_config',
            field=models.JSONField(blank=True, help_text='This configuration is specifically used for raw data popup.It is list of {name, alias, type, visible}', null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicatorlayer',
            name='raw_data_popup_enable',
            field=models.BooleanField(default=False, help_text='This popup will be used for showing raw data on popup.Example: Showing related table data on popup.'),
        ),
    ]
