# Generated by Django 3.2.16 on 2025-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0130_auto_20251024_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='country_concept_uuid',
            field=models.CharField(blank=True, help_text='This is concept uuid from georepo.', max_length=256, null=True),
        ),
    ]
