# Generated by Django 3.2.16 on 2025-10-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0130_auto_20251024_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='country_concept_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='This is concept uuid from georepo.', max_length=256, null=True),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['indicator', 'country_concept_uuid'], name='geosight_da_indicat_d60eaa_idx'),
        ),
    ]
