# Generated by Django 3.2.16 on 2025-11-10 09:02

from django.db import migrations, models

def run(apps, schema_editor):
    SDMXConfig = apps.get_model("geosight_data", "SDMXConfig")
    SDMXConfig.objects.get_or_create(
        name="Unicef SDMX Default",
        url="https://sdmx.data.unicef.org/ws/public/sdmxapi/rest/"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0131_auto_20251029_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDMXConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
