# Generated by Django 3.2.16 on 2025-12-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0132_sdmxconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
