# Generated by Django 3.2.16 on 2026-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0133_dashboard_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='max_zoom',
            field=models.IntegerField(blank=True, help_text='Maximum zoom level for the dashboard', null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='min_zoom',
            field=models.IntegerField(blank=True, help_text='Minimum zoom level for the dashboard', null=True),
        ),
    ]
