# Generated by Django 3.2.16 on 2026-02-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0135_dashboardcachepermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='cache_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='cache_data_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
