# Generated by Django 3.2.16 on 2026-03-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_data', '0136_auto_20260227_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemaplayer',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basemaplayer',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contextlayer',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboardembed',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboardembed',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relatedtable',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relatedtable',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zonalanalysis',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zonalanalysis',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_basemaplayer_related', related_query_name='geosight_data_basemaplayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_basemaplayer_modified_by_related', related_query_name='geosight_data_basemaplayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_contextlayer_related', related_query_name='geosight_data_contextlayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_contextlayer_modified_by_related', related_query_name='geosight_data_contextlayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_dashboard_related', related_query_name='geosight_data_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_dashboard_modified_by_related', related_query_name='geosight_data_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardembed',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_dashboardembed_related', related_query_name='geosight_data_dashboardembeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardembed',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_dashboardembed_modified_by_related', related_query_name='geosight_data_dashboardembeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_indicator_related', related_query_name='geosight_data_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_indicator_modified_by_related', related_query_name='geosight_data_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatedtable',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_relatedtable_related', related_query_name='geosight_data_relatedtables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatedtable',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_relatedtable_modified_by_related', related_query_name='geosight_data_relatedtables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='style',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_style_related', related_query_name='geosight_data_styles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='style',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_style_modified_by_related', related_query_name='geosight_data_styles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zonalanalysis',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_zonalanalysis_related', related_query_name='geosight_data_zonalanalysiss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zonalanalysis',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_data_zonalanalysis_modified_by_related', related_query_name='geosight_data_zonalanalysiss', to=settings.AUTH_USER_MODEL),
        ),
    ]
