# Generated by Django 3.2.16 on 2026-03-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0137_auto_20260302_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardrelationgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_data.dashboardrelationgroup'),
        ),
    ]
