# Generated by Django 3.2.16 on 2026-03-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0138_alter_dashboardrelationgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcontextlayer',
            name='layer_description',
            field=models.TextField(blank=True, help_text='Overridden of description of the context layer', null=True),
        ),
        migrations.AddField(
            model_name='dashboardcontextlayer',
            name='layer_name',
            field=models.CharField(blank=True, help_text='Overridden of name of the context layer', max_length=512, null=True),
        ),
    ]
