# Generated by Django 3.2.16 on 2026-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0139_auto_20260311_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextlayer',
            name='label_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardcontextlayer',
            name='label_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
