# Generated by Django 3.2.16 on 2026-03-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0140_auto_20260312_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='auto_zoom_to_filter',
            field=models.BooleanField(default=False),
        ),
    ]
