# Generated by Django 3.2.16 on 2026-03-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0141_dashboard_auto_zoom_to_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='stories_structure',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='story_map_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DashboardStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('order', models.IntegerField(default=0)),
                ('visible_by_default', models.BooleanField(default=False)),
                ('group', models.CharField(blank=True, max_length=512, null=True)),
                ('relation_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_data.dashboardrelationgroup')),
                ('config', models.JSONField(blank=True, null=True)),
                ('bookmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geosight_data.dashboardbookmark')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_data.dashboard')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
