# Generated by Django 3.2.16 on 2026-04-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0142_auto_20260413_0642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorValueDataset',
        ),
    ]
