# Generated by Django 3.2.16 on 2026-03-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0142_dashboard_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstory',
            name='relation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_data.dashboardrelationgroup'),
        ),
    ]
