# Generated by Django 3.2.16 on 2026-04-21 10:12

from django.db import migrations, models


def set_override_fields_true(apps, schema_editor):
    DashboardContextLayer = apps.get_model('geosight_data', 'DashboardContextLayer')
    DashboardIndicatorLayer = apps.get_model('geosight_data', 'DashboardIndicatorLayer')

    DashboardContextLayer.objects.all().update(
        override_layer_description=True,
        override_layer_name=True,
    )
    DashboardIndicatorLayer.objects.all().update(
        override_description=True,
        override_name=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0142_auto_20260413_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcontextlayer',
            name='override_layer_description',
            field=models.BooleanField(default=False, help_text="If set to false, the object's description will be used."),
        ),
        migrations.AddField(
            model_name='dashboardcontextlayer',
            name='override_layer_name',
            field=models.BooleanField(default=False, help_text="If set to false, the object's name will be used."),
        ),
        migrations.AddField(
            model_name='dashboardindicatorlayer',
            name='override_description',
            field=models.BooleanField(default=False, help_text="If set to false, the object's name will be used."),
        ),
        migrations.AddField(
            model_name='dashboardindicatorlayer',
            name='override_name',
            field=models.BooleanField(default=False, help_text="If set to false, the object's name will be used."),
        ),
        migrations.AlterField(
            model_name='dashboardcontextlayer',
            name='override_field',
            field=models.BooleanField(default=False, help_text="If set to false, the object's fields will be used."),
        ),
        migrations.AlterField(
            model_name='dashboardcontextlayer',
            name='override_label',
            field=models.BooleanField(default=False, help_text="If set to false, the object's label will be used."),
        ),
        migrations.AlterField(
            model_name='dashboardcontextlayer',
            name='override_style',
            field=models.BooleanField(default=False, help_text="If set to false, the object's styles will be used."),
        ),
        migrations.RunPython(
            set_override_fields_true,
            migrations.RunPython.noop,
        ),
    ]
