# Generated by Django 3.2.16 on 2026-04-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0143_auto_20260421_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardindicatorlayer',
            name='type',
            field=models.CharField(choices=[('Single Indicator', 'Single Indicator'), ('Multi Indicator', 'Multi Indicator'), ('Dynamic Indicator', 'Dynamic Indicator'), ('Related Table', 'Related Table'), ('TYPE_SDMX', 'TYPE_SDMX')], default='Single Indicator', max_length=48),
        ),
    ]
