# Generated by Django 3.2.16 on 2026-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0144_alter_dashboardindicatorlayer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicatorlayer',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdmxconfig',
            name='agency_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sdmxconfig',
            name='agency_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sdmxconfig',
            name='dataflow_dsd_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sdmxconfig',
            name='dataflow_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sdmxconfig',
            name='dataflow_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sdmxconfig',
            name='dataflow_version_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
