# Generated by Django 3.2.16 on 2026-05-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0144_alter_dashboardindicatorlayer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdmxconfig',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
