# Generated by Django 3.2.16 on 2026-05-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0145_sdmxconfig_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicatorlayer',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
