# Generated by Django 3.2.16 on 2026-06-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0145_auto_20260512_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbookmark',
            name='map_mode',
            field=models.CharField(blank=True, help_text='Map mode of the dashboard. is it compare_layers or side_by_side_view.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboardembed',
            name='map_mode',
            field=models.CharField(blank=True, help_text='Map mode of the dashboard. is it compare_layers or side_by_side_view.', max_length=255, null=True),
        ),
    ]
