# Generated by Django 3.2.16 on 2026-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupDirectoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('storage_path', models.TextField(help_text='The path of the storage that was cleaned up.')),
                ('usage_percentage', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('deleted_files_count', models.PositiveIntegerField(blank=True, null=True)),
                ('freed_space_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('deleted_files', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
