# Generated by Django 3.2.16 on 2023-09-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_permission', '0009_alter_relatedtablepermission_organization_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedtablepermission',
            name='public_permission',
            field=models.CharField(choices=[('None', 'None'), ('Read Data', 'Read Data')], default='None', max_length=16),
        ),
    ]
