# Generated by Django 3.2.16 on 2023-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_permission', '0010_alter_relatedtablepermission_public_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylepermission',
            name='public_permission',
            field=models.CharField(choices=[('None', 'None'), ('Read Data', 'Read Data')], default='None', max_length=16),
        ),
    ]
