# Generated by Django 3.2.16 on 2023-11-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_permission', '0013_views_initiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayerIndicatorPermissionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.IntegerField()),
                ('identifier', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'v_referencelayer_indicator_permission',
                'managed': False,
            },
        ),
    ]
