# Generated by Django 3.2.16 on 2024-07-23 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_permission', '0014_referencelayerindicatorpermissionview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodelpermission',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_permission_groupmodelpermission_related', related_query_name='geosight_permission_groupmodelpermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
