# Generated by Django 3.2.16 on 2024-06-06 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_cloud_native_gis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('geosight_permission', '0014_referencelayerindicatorpermissionview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudNativeGISLayerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('organization_permission', models.CharField(choices=[('None', 'None'), ('List', 'List'), ('Read', 'Read')], default='Read', max_length=16)),
                ('public_permission', models.CharField(choices=[('None', 'None'), ('Read', 'Read')], default='Read', max_length=16)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='geosight_cloud_native_gis.cloudnativegislayer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudNativeGISLayerUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('List', 'List'), ('Read', 'Read'), ('Write', 'Write'), ('Share', 'Share'), ('Owner', 'Owner')], default='Read', max_length=16)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='geosight_permission.cloudnativegislayerpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('obj', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CloudNativeGISLayerGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('List', 'List'), ('Read', 'Read'), ('Write', 'Write'), ('Share', 'Share'), ('Owner', 'Owner')], default='Read', max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='geosight_permission.cloudnativegislayerpermission')),
            ],
            options={
                'abstract': False,
                'unique_together': {('obj', 'group')},
            },
        ),
    ]
