# Generated by Django 3.2.16 on 2026-03-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_permission', '0017_auto_20250407_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodelpermission',
            name='creator_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupmodelpermission',
            name='modified_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupmodelpermission',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_permission_groupmodelpermission_related', related_query_name='geosight_permission_groupmodelpermissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmodelpermission',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geosight_permission_groupmodelpermission_modified_by_related', related_query_name='geosight_permission_groupmodelpermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
