# Generated by Django 3.2.16 on 2026-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_permission', '0018_auto_20260302_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodelpermission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
