# Generated by Django 3.2.16 on 2023-11-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_importer', '0018_alter_importer_input_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importerattribute',
            name='name',
            field=models.CharField(help_text='The name of attribute', max_length=512),
        ),
        migrations.AlterField(
            model_name='importermapping',
            name='name',
            field=models.CharField(help_text='The name of attribute', max_length=512),
        ),
    ]
