# Generated by Django 3.2.16 on 2024-06-06 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_importer', '0019_auto_20231108_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_importer_importer_related', related_query_name='geosight_importer_importers', to=settings.AUTH_USER_MODEL),
        ),
    ]
