# Generated by Django 3.2.16 on 2025-01-14 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_importer', '0020_alter_importer_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='importer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_importer_importer_modified_by_related', related_query_name='geosight_importer_importers', to=settings.AUTH_USER_MODEL),
        ),
    ]
