# Generated by Django 3.2.16 on 2025-02-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_importer', '0021_importer_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerlog',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importerlog',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
