# Generated by Django 3.2.16 on 2023-08-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation_base_url', models.CharField(default='https://unicef-drp.github.io/GeoSight-OS/', max_length=512)),
            ],
            options={
                'verbose_name_plural': 'documentation preferences',
            },
        ),
    ]
