# Generated by Django 3.2.16 on 2023-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='relative_url',
            field=models.CharField(blank=True, help_text='Relative page url as identifier to be matched for the page that are opened. Example: put `/project`, it will use this page as help center when we are in /project.', max_length=128, null=True, verbose_name='Relative Page Url'),
        ),
        migrations.AlterField(
            model_name='block',
            name='anchor',
            field=models.CharField(blank=True, help_text='Anchor of block on the page on the documentation. This will be used as a start or the content.If the anchor is not provided, it will use whole content.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, help_text='If no description is provided, it will use the first paragraph from the help center under the anchor specified above will be used. We recommend to normally leave this blank', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='If no thumbnail is provided, it will use the first image in the help page under the anchor specified above will be used. We recommend to normally leave this blank', null=True, upload_to='docs/icons'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, help_text='If no title is provided, it will use the title of the anchor on documentation page.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='url',
            field=models.CharField(help_text='Relative url of documentation base url that will be used to autofetch the content and also will be used as "Visit our documentation" button.', max_length=128, verbose_name='Relative Documentation Url'),
        ),
        migrations.AlterField(
            model_name='page',
            name='intro',
            field=models.TextField(blank=True, help_text='Help intro for this page help center, below title and upper of blocks.', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Title that will be used on the page help center.', max_length=512),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(help_text='Relative url of documentation base url that will be used as "Visit our documentation" button.', max_length=128, verbose_name='Relative Documentation Url'),
        ),
    ]
