# Generated by Django 3.2.16 on 2026-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20230904_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='autogenerate_block',
            field=models.BooleanField(default=True, help_text='Autogenerate blocks from the documentation. If unchecked, it will use blocks child of this page.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, help_text='If no title is provided, it will use the title of the anchor on documentation page.', max_length=512, null=True),
        ),
    ]
