# Generated by Django 3.2.16 on 2024-05-03 07:43

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import timezone_field.fields
from django.db import migrations, models

from tenants.models import Client, Domain


class Migration(migrations.Migration):
    initial = True

    def run(apps, schema_editor):
        client, _ = Client.objects.get_or_create(
            schema_name='public', name='Main'
        )
        Domain.objects.get_or_create(
            domain='localhost',
            tenant=client, defaults={
                'is_primary': True
            }
        )

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'schema_name',
                    models.CharField(
                        db_index=True, max_length=63, unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ]
                    )
                ),
                (
                    'timezone',
                    timezone_field.fields.TimeZoneField(default='UTC')
                ),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodicTaskTenantLink',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                ('use_tenant_timezone', models.BooleanField(default=False)),
                (
                    'periodic_task', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='periodic_task_tenant_link',
                        to='django_celery_beat.periodictask'
                    )
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='periodic_task_tenant_links',
                        to='tenants.client'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'domain',
                    models.CharField(
                        db_index=True, max_length=253, unique=True
                    )
                ),
                (
                    'is_primary',
                    models.BooleanField(db_index=True, default=True)
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='domains',
                        to='tenants.client')
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
