# Generated by Django 3.2.16 on 2024-08-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDataLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_field_group', models.CharField(blank=True, help_text='The model field group that will be used to group the limitation. e.g: Limit a Model by the field group. If it is empty, it will limit all of data.', max_length=126, null=True)),
                ('limit', models.IntegerField(blank=True, help_text='Limit of data allowed to the content_type.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.client')),
            ],
            options={
                'ordering': ('content_type',),
                'unique_together': {('content_type', 'model_field_group')},
            },
        ),
    ]
