# Generated by Django 3.2.16 on 2023-10-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0014_entity_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['geom_id'], name='entity_geom_id'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['concept_uuid'], name='concept_uuid'),
        ),
    ]
