# Generated by Django 3.2.16 on 2024-02-12 03:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0016_referencelayerview_version_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayerViewLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(help_text='Level name.', max_length=256)),
                ('reference_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerview')),
            ],
            options={
                'unique_together': {('reference_layer', 'level')},
            },
        ),
        migrations.DeleteModel(
            name='ReferenceLayer',
        ),
        migrations.AddField(
            model_name='entity',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
