# Generated by Django 3.2.16 on 2024-02-22 04:01

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_georepo', '0016_referencelayerview_version_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayerViewLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(help_text='Level name.', max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='ReferenceLayer',
        ),
        migrations.AddField(
            model_name='entity',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='entity',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='referencelayerview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='referencelayerview',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencelayerview',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='referencelayerview',
            index=models.Index(fields=['identifier'], name='reference_layer_identifier'),
        ),
        migrations.AddField(
            model_name='referencelayerviewlevel',
            name='reference_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerview'),
        ),
        migrations.AlterUniqueTogether(
            name='referencelayerviewlevel',
            unique_together={('reference_layer', 'level')},
        ),
    ]
