# Generated by Django 3.2.16 on 2024-02-13 05:21

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_georepo', '0017_auto_20240212_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayerViewImporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Reference layer name.', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Start', 'Start'), ('Running', 'Running'), ('Failed', 'Failed'), ('Success', 'Success')], default='Start', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceLayerViewTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Reference layer identifier.', max_length=256)),
                ('name', models.CharField(blank=True, help_text='Reference layer name.', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerviewimporter')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceLayerViewImporterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='georepo/importers')),
                ('level', models.IntegerField()),
                ('name', models.CharField(help_text='Level name.', max_length=256)),
                ('name_field', models.CharField(help_text='Field indicate the name.', max_length=256)),
                ('ucode_field', models.CharField(help_text='Field indicate the ucode.', max_length=256)),
                ('parent_ucode_field', models.CharField(blank=True, help_text='Field indicate the parent ucode. This is just 1 level above it.', max_length=256, null=True)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerviewimporter')),
            ],
        ),
        migrations.CreateModel(
            name='EntityTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents', models.JSONField(blank=True, help_text='List of parents, ordered by most bottom to top.', null=True)),
                ('admin_level', models.IntegerField(blank=True, null=True)),
                ('geom_id', models.CharField(help_text='This is ucode from georepo.', max_length=256)),
                ('concept_uuid', models.CharField(blank=True, help_text='This is concept uuid from georepo.', max_length=256, null=True)),
                ('name', models.CharField(help_text='label of entity.', max_length=512)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('reference_layer', models.ForeignKey(help_text='Reference layer.', on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerviewtemp')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceLayerViewLevelTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(help_text='Level name.', max_length=256)),
                ('reference_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerviewtemp')),
            ],
            options={
                'unique_together': {('reference_layer', 'level')},
            },
        ),
    ]
