# Generated by Django 3.2.16 on 2024-02-22 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_georepo', '0017_auto_20240222_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayerViewImporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Waiting files', 'Waiting files'), ('Start', 'Start'), ('Running', 'Running'), ('Failed', 'Failed'), ('Success', 'Success')], default='Waiting files', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceLayerViewImporterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('file_id', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(upload_to='georepo/importers')),
                ('properties', models.JSONField(blank=True, null=True)),
                ('name_field', models.CharField(help_text='Field indicate the name.', max_length=256)),
                ('ucode_field', models.CharField(help_text='Field indicate the ucode.', max_length=256)),
                ('parent_ucode_field', models.CharField(blank=True, help_text='Field indicate the parent ucode. This is just 1 level above it.', max_length=256, null=True)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerviewimporter')),
            ],
            options={
                'ordering': ('level',),
            },
        ),
    ]
