# Generated by Django 3.2.16 on 2024-02-12 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_georepo', '0017_auto_20240212_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayerViewUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Reference layer name.', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceLayerViewUploaderLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='georepo/importers')),
                ('level', models.IntegerField()),
                ('name', models.CharField(help_text='Level name.', max_length=256)),
                ('name_column', models.CharField(help_text='Column indicate the name.', max_length=256)),
                ('ucode_column', models.CharField(help_text='Column indicate the ucode.', max_length=256)),
                ('parent_ucode_column', models.CharField(blank=True, help_text='Column indicate the parent ucode. This is just 1 level above it.', max_length=256, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerviewuploader')),
            ],
        ),
    ]
