# Generated by Django 3.2.16 on 2024-02-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0018_auto_20240213_0701'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referencelayerview',
            index=models.Index(fields=['identifier'], name='reference_layer_identifier'),
        ),
    ]
