# Generated by Django 3.2.16 on 2024-08-12 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_georepo', '0018_referencelayerviewimporter_referencelayerviewimporterlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencelayerview',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_georepo_referencelayerview_related', related_query_name='geosight_georepo_referencelayerviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencelayerviewimporter',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosight_georepo_referencelayerviewimporter_related', related_query_name='geosight_georepo_referencelayerviewimporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
