# Generated by Django 3.2.16 on 2025-02-03 05:49

from django.db import migrations


class Migration(migrations.Migration):
    sql = """
        DELETE FROM geosight_georepo_entitycode;
        DELETE FROM geosight_georepo_entity
            WHERE reference_layer_id IN (
                SELECT view.id
                FROM geosight_georepo_referencelayerview AS view
                WHERE view.in_georepo = True
            );
    """

    dependencies = [
        ('geosight_georepo', '0018_referencelayerview_modified_by'),
    ]

    operations = [
        migrations.RunSQL(sql, migrations.RunPython.noop),
    ]
