# Generated by Django 3.2.16 on 2025-02-04 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0019_delete_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='geom_id',
            field=models.CharField(help_text='This is ucode from georepo.', max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ReferenceLayerViewEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.entity')),
                ('reference_layer_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayerview')),
            ],
            options={
                'verbose_name_plural': 'reference layer view entities',
            },
        ),
        migrations.AddIndex(
            model_name='referencelayerviewentity',
            index=models.Index(fields=['entity', 'reference_layer_view'], name='reference_layer_view_entity'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['concept_uuid', 'reference_layer', 'admin_level'], name='geosight_ge_concept_423396_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['id', 'reference_layer'], name='geosight_ge_id_ddda21_idx'),
        ),
    ]
