# Generated by Django 3.2.16 on 2024-02-15 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_georepo', '0019_referencelayerview_reference_layer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencelayerview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='referencelayerview',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencelayerview',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
