# Generated by Django 3.2.16 on 2025-02-03 05:49

from django.db import migrations


def run(apps, schema_editor):
    Entity = apps.get_model(
        "geosight_georepo", "Entity"
    )
    ReferenceLayerViewEntity = apps.get_model(
        "geosight_georepo", "ReferenceLayerViewEntity"
    )
    for entity in Entity.objects.filter(reference_layer__isnull=False):
        ReferenceLayerViewEntity.objects.get_or_create(
            reference_layer_view=entity.reference_layer,
            entity=entity,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('geosight_georepo', '0020_auto_20250204_0556'),
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
