# Generated by Django 3.2.16 on 2025-03-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0021_auto_20250203_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country of the entity. If null, it is the country of the entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_georepo.entity'),
        ),
        migrations.AddField(
            model_name='referencelayerview',
            name='countries',
            field=models.ManyToManyField(help_text='The country of the view.', null=True, to='geosight_georepo.Entity'),
        ),
    ]
