# Generated by Django 3.2.16 on 2025-04-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0022_auto_20250305_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencelayerview',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
