# Generated by Django 3.2.16 on 2025-02-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0022_entity_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencelayerview',
            name='countries',
            field=models.ManyToManyField(help_text='The country of the view.', null=True, to='geosight_georepo.Entity'),
        ),
    ]
