# Generated by Django 3.2.16 on 2026-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_request', models.BooleanField(default=True, help_text='Enable request to restore fixture.It will be disabled if there is a color palette.')),
            ],
            options={
                'verbose_name_plural': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='RequestRestoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('Default', 'Default'), ('Demo', 'Demo')], max_length=255)),
                ('state', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('finish', 'Finish'), ('failed', 'Failed')], default='created', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
    ]
