# Generated by Django 3.2.16 on 2026-04-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data_restorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestrestoredata',
            options={'verbose_name_plural': 'request restore data'},
        ),
    ]
