# Generated by Django 3.2.16 on 2026-04-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data_restorer', '0002_alter_requestrestoredata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='is_kartoza_data_restored',
            field=models.BooleanField(default=False, help_text='Indicates whether default data has been restored.'),
        ),
    ]
