# Generated by Django 3.2.16 on 2026-04-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data_restorer', '0003_preferences_is_default_data_restored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrestoredata',
            name='data_type',
            field=models.CharField(choices=[('Country demo data', 'Country demo data')], max_length=255),
        ),
    ]
