# Generated by Django 3.2.16 on 2023-05-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_sitepreferences_site_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='georepo_api_key',
            new_name='georepo_api_key_level_4',
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='georepo_api_key_level_1',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='georepo_api_key_level_4',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('Contributor', 'Contributor'), ('Creator', 'Creator'), ('Super Admin', 'Super Admin')], default='Creator', max_length=16),
        ),
    ]
