# Generated by Django 3.2.16 on 2023-07-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230525_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='indicator_no_data_fill_color',
            new_name='style_no_data_fill_color',
        ),
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='indicator_no_data_outline_color',
            new_name='style_no_data_outline_color',
        ),
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='indicator_other_data_fill_color',
            new_name='style_other_data_fill_color',
        ),
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='indicator_other_data_outline_color',
            new_name='style_other_data_outline_color',
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='style_dynamic_style_outline_size',
            field=models.FloatField(default=0.5, help_text='Default outline size for dynamic style.'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='style_new_rule_fill_color',
            field=models.CharField(default='#000000', help_text='Default fill color for new rule style.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='style_new_rule_outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Default outline color for new rule style.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='style_new_rule_outline_size',
            field=models.FloatField(default=0.5, help_text='Default outline size for new rule style.'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='style_no_data_outline_size',
            field=models.FloatField(default=0.5, help_text='Default outline size for no data style.'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='style_other_data_outline_size',
            field=models.FloatField(default=0.5, help_text='Default outline size for other data style.'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='style_dynamic_style_outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Default outline color for dynamic style.', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_no_data_fill_color',
            field=models.CharField(default='#D8D8D8', help_text='Default fill color for no data style.', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_no_data_outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Default outline color for no data style.', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_other_data_fill_color',
            field=models.CharField(default='#A6A6A6', help_text='Default fill color for other data style.', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_other_data_outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Default outline color for other data style.', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_dynamic_style_outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Default outline color for dynamic style.', max_length=16, verbose_name='Outline color'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_dynamic_style_outline_size',
            field=models.FloatField(default=0.5, help_text='Default outline size for dynamic style.', verbose_name='Outline size'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_new_rule_fill_color',
            field=models.CharField(default='#000000', help_text='Default fill color for new rule style.', max_length=16, verbose_name='Fill color'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_new_rule_outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Default outline color for new rule style.', max_length=16, verbose_name='Outline color'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_new_rule_outline_size',
            field=models.FloatField(default=0.5, help_text='Default outline size for new rule style.', verbose_name='Outline size'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_no_data_fill_color',
            field=models.CharField(default='#D8D8D8', help_text='Default fill color for no data style.', max_length=16, verbose_name='Fill color'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_no_data_outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Default outline color for no data style.', max_length=16, verbose_name='Outline color'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_no_data_outline_size',
            field=models.FloatField(default=0.5, help_text='Default outline size for no data style.', verbose_name='Outline size'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_other_data_fill_color',
            field=models.CharField(default='#A6A6A6', help_text='Default fill color for other data style.', max_length=16, verbose_name='Fill color'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_other_data_outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Default outline color for other data style.', max_length=16, verbose_name='Outline color'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='style_other_data_outline_size',
            field=models.FloatField(default=0.5, help_text='Default outline size for other data style.', verbose_name='Outline size'),
        ),
    ]
