# Generated by Django 3.2.16 on 2023-07-25 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20230724_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='default_admin_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEW_USER', 'NEW_USER'), ('NEW_PERMISSIONS', 'NEW_PERMISSIONS')], max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('submitted_on', models.DateTimeField()),
                ('requester_first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('requester_last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('requester_email', models.EmailField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approver_notes', models.CharField(blank=True, max_length=512, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessrequests_approval', to=settings.AUTH_USER_MODEL)),
                ('request_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessrequests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
