# Generated by Django 3.2.16 on 2023-07-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230725_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='landing_page_banner',
            field=models.FileField(blank=True, null=True, upload_to='settings/images'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='landing_page_banner_text',
            field=models.TextField(default=''),
        ),
    ]
