# Generated by Django 3.2.16 on 2023-07-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230727_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='style_compare_mode_outline_size',
            field=models.FloatField(default=4, help_text='Outline size for compare mode.', verbose_name='Outline size'),
        ),
    ]
