# Generated by Django 3.2.16 on 2023-08-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitepreferences_style_compare_mode_outline_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='georepo_azure_authentication_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
