# Generated by Django 3.2.16 on 2023-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_sitepreferences_landing_page_banner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreferences',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/icons'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/icons'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='landing_page_banner',
            field=models.ImageField(blank=True, null=True, upload_to='settings/images'),
        ),
        migrations.AlterField(
            model_name='sitepreferencesimage',
            name='image',
            field=models.ImageField(upload_to='settings/images'),
        ),
    ]
