# Generated by Django 3.2.16 on 2023-08-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230822_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepreferences',
            name='georepo_azure_authentication_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='georepo_api_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='georepo_api_key_level_1_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='georepo_api_key_level_4_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='georepo_using_user_api_key',
            field=models.BooleanField(default=True),
        ),
    ]
