# Generated by Django 3.2.16 on 2023-09-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230824_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepreferences',
            name='default_admin_emails',
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_notification',
            field=models.BooleanField(default=False, help_text='Designates whether the user receive notification.'),
        ),
    ]
