# Generated by Django 3.2.16 on 2023-09-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230907_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='default_basemap',
            field=models.IntegerField(blank=True, help_text='Basemap that will be autoadded to new project if user has list access.', null=True),
        ),
    ]
