# Generated by Django 3.2.16 on 2023-09-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sitepreferences_default_basemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='default_color_palette',
            field=models.ForeignKey(blank=True, help_text='Color palette that will be autoadded to new indicator when dynamic style is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.colorpalette'),
        ),
    ]
