# Generated by Django 3.2.16 on 2023-10-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sitepreferences_default_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='default_interval',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='fit_to_current_indicator_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='show_last_known_value_in_range',
            field=models.BooleanField(default=True),
        ),
    ]
