# Generated by Django 3.2.16 on 2024-06-06 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_sitepreferences_login_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_maintenance_related', related_query_name='core_maintenances', to=settings.AUTH_USER_MODEL),
        ),
    ]
