# Generated by Django 3.2.16 on 2024-08-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_maintenance_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manage_local_dataset',
            field=models.BooleanField(default=False, help_text='Designates whether the user able to manage local dataset.'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='enable_georepo',
            field=models.BooleanField(default=True, help_text='Enable GeoRepo to use local datasets alongside local dataset.'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='enable_local_dataset',
            field=models.BooleanField(default=True, help_text='Enable feature to use local datasets alongside georepo.'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='login_help_text',
            field=models.TextField(blank=True, default='', help_text='Help text to show in login page.', null=True),
        ),
    ]
