# Generated by Django 3.2.16 on 2024-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_maintenance_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='site_type',
            field=models.CharField(choices=[('Staging', 'Staging'), ('Production', 'Production')], default='Production', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='login_help_text',
            field=models.TextField(blank=True, default='', help_text='Help text to show in login page.', null=True),
        ),
    ]
