# Generated by Django 3.2.16 on 2024-10-22 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20241014_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='scheduled_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Scheduled time from.'),
        ),
    ]
