# Generated by Django 3.2.16 on 2024-10-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_maintenance_scheduled_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='machine_info_fetcher_config',
            field=models.JSONField(default={'api_key': '', 'user_email': ''}, help_text='Config for machine info fetcher.'),
        ),
    ]
