# Generated by Django 3.2.16 on 2024-11-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sitepreferences_machine_info_fetcher_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('size', models.PositiveBigIntegerField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
