# Generated by Django 3.2.16 on 2025-01-14 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_sitepreferences_machine_info_fetcher_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_maintenance_modified_by_related', related_query_name='core_maintenances', to=settings.AUTH_USER_MODEL),
        ),
    ]
