# Generated by Django 3.2.16 on 2024-11-13 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_logfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogFile',
        ),
    ]
