# Generated by Django 3.2.16 on 2025-04-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_maintenance_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='contact_us_url',
            field=models.TextField(blank=True, default='', help_text='Add a Contact Us URL in the Help section. You can use a mailto: link, like mailto:example@email.com, to allow users to send an email.', null=True),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='send_feedback_url',
            field=models.TextField(blank=True, default='', help_text='Add a feedback URL in the Help section. You can use a mailto: link, like mailto:example@email.com, to allow users to send an email.', null=True),
        ),
    ]
