# Generated by Django 3.2.16 on 2025-08-14 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20250409_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='small_icon',
            field=models.FileField(blank=True, null=True, upload_to='settings/icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='settings/icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='settings/icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gif'])]),
        ),
    ]
