# Generated by Django 3.2.16 on 2025-10-24 05:28

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20250814_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code in #RRGGBB or #RRGGBBAA format.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$')]), size=None),
        ),
    ]
