# Generated by Django 3.2.16 on 2025-11-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0023_referencelayerview_tags'),
        ('core', '0038_alter_colorpalette_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='georepo_default_view',
            field=models.ForeignKey(blank=True, help_text='Default view for georepo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_georepo.referencelayerview'),
        ),
    ]
