# Generated by Django 3.2.16 on 2026-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_maintenance_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreferences',
            name='georepo_api_key_level_1',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='georepo_api_key_level_4',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='georepo_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='site_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
