import logging
import mkdocs.plugins
import os

log = logging.getLogger('mkdocs')

@mkdocs.plugins.event_priority(-50)


def on_startup(command, dirty):


    template = """
---
title: Automatically Generated Python Documentation
summary: DO NOT EDIT THIS FILE MANUALLY : It is created during the mkdocs build process
date: 2023-08-03
---

# Python Reference Manual
"""
    ignore_list = [ 
    	"__init__",
    	"migrations",
        "tests"]

    for root, dirs, files in os.walk("../django_project"):
        for file in files:
            file = os.path.join(root, file)
            if file.endswith(".py"):
                ignored = False;
                for item in ignore_list:
                    if item in file:
                        ignored = True;
                    #print (item, file, ignored)
                if not ignored:
                    file = file.replace("../django_project/", "::: ")
                    file = file.replace("/", ".")
                    file = file.replace(".py", "")
                    template = template + file + "\n"
    file = open("docs/src/developer/manual/index.md","wt")
    file.write(template)
    file.close()
